FROM --platform=$BUILDPLATFORM golang:1.21.6 AS build
ARG TARGETARCH

WORKDIR /go/src/github.com/jpubdocker/echo
COPY . .

RUN GOARCH=${TARGETARCH} CGO_ENABLED=0 go build -o bin/echo main.go

FROM gcr.io/distroless/base-debian11:debug
LABEL org.opencontainers.image.source=https://github.com/jpubdocker/echo

COPY --from=build /go/src/github.com/jpubdocker/echo/bin/echo /usr/local/bin/

CMD ["echo"]
